# CMake generated Testfile for 
# Source directory: /home/toxiccclub/opengv
# Build directory: /home/toxiccclub/opengv/build_arm64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_absolute_pose "/home/toxiccclub/opengv/build_arm64/bin/test_absolute_pose")
set_tests_properties(test_absolute_pose PROPERTIES  WORKING_DIRECTORY "/home/toxiccclub/opengv/build_arm64/bin" _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;205;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_absolute_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_absolute_pose_sac")
set_tests_properties(test_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;211;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose "/home/toxiccclub/opengv/build_arm64/bin/test_noncentral_absolute_pose")
set_tests_properties(test_noncentral_absolute_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;217;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_noncentral_absolute_pose_sac")
set_tests_properties(test_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;223;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_absolute_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_multi_noncentral_absolute_pose_sac")
set_tests_properties(test_multi_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;229;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose "/home/toxiccclub/opengv/build_arm64/bin/test_relative_pose")
set_tests_properties(test_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;235;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly "/home/toxiccclub/opengv/build_arm64/bin/test_relative_pose_rotationOnly")
set_tests_properties(test_relative_pose_rotationOnly PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;241;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly_sac "/home/toxiccclub/opengv/build_arm64/bin/test_relative_pose_rotationOnly_sac")
set_tests_properties(test_relative_pose_rotationOnly_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;247;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_relative_pose_sac")
set_tests_properties(test_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;253;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose "/home/toxiccclub/opengv/build_arm64/bin/test_noncentral_relative_pose")
set_tests_properties(test_noncentral_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;259;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_noncentral_relative_pose_sac")
set_tests_properties(test_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;265;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_relative_pose_sac "/home/toxiccclub/opengv/build_arm64/bin/test_multi_noncentral_relative_pose_sac")
set_tests_properties(test_multi_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;271;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver_sac "/home/toxiccclub/opengv/build_arm64/bin/test_eigensolver_sac")
set_tests_properties(test_eigensolver_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;277;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_triangulation "/home/toxiccclub/opengv/build_arm64/bin/test_triangulation")
set_tests_properties(test_triangulation PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;283;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver "/home/toxiccclub/opengv/build_arm64/bin/test_eigensolver")
set_tests_properties(test_eigensolver PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;289;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud "/home/toxiccclub/opengv/build_arm64/bin/test_point_cloud")
set_tests_properties(test_point_cloud PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;295;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud_sac "/home/toxiccclub/opengv/build_arm64/bin/test_point_cloud_sac")
set_tests_properties(test_point_cloud_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;301;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
add_test(test_Sturm "/home/toxiccclub/opengv/build_arm64/bin/test_Sturm")
set_tests_properties(test_Sturm PROPERTIES  _BACKTRACE_TRIPLES "/home/toxiccclub/opengv/CMakeLists.txt;307;add_test;/home/toxiccclub/opengv/CMakeLists.txt;0;")
